sudo: required
services:
  - docker

before_install:
  - docker build -t yukiumetsu/docker-react-setup -f Dockerfile.dev .

script:
  - docker run -e CI=true yukiumetsu/docker-react-setup npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-setup"
  env: "Dockerreactsetup-env"
  bucket_name: "elasticbeanstalk-us-east-2-085618038075"
  bucket_path: "docker-react-setup"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY